Initialize as admin when in public mode
saurabhshri/ccextractor-web pull request #15
Opened 2018-11-17 18:28 UTC by T1duS

Fixed https://github.com/saurabhshri/ccextractor-web/issues/13

2018-11-18 11:50 UTC, saurabhshri requested changes
Thank you for the PR! :) Could you please test it again? From the first look - it doesn't look like there's any difference between both the modes right now. Could you please re-check?

2018-11-18 12:28 UTC, T1duS commented
@saurabhshri Only the initializing part is same for both modes.

2018-11-18 17:29 UTC, saurabhshri commented
But why? We don't want to have admin account logged in by default in `Public Mode`. 😉

2018-11-18 17:31 UTC, T1duS commented
@saurabhshri How is this different from the issue?

2018-11-18 17:41 UTC, saurabhshri commented
The issue is that when initialised in public mode, no admin account exist. The user needs to be granted admin role manually by editing the db entry. We want to create a default admin account in both the cases, but not login by default in public mode.

2018-11-20 20:00 UTC, saurabhshri commented
Could you please put the common code (of admin account creation) above the if-else statements so that's it's not repetitive? Thanks!

2018-11-21 11:21 UTC, saurabhshri commented on run.py
```suggestion
    log.debug('INIT : Creating admin account.')
```

2018-11-22 14:35 UTC, saurabhshri reviewed
Looks good, could you please add a test to see if admin user is added successfully?

2018-11-23 09:27 UTC, saurabhshri commented on tests/test_running_app.py
> +        self.assertNotEqual(user, None)
Please add a newline at the end. :)

2018-11-23 10:44 UTC, saurabhshri requested changes
Looks good! We're close to merge. Now only the documentation needs to be edited to reflect theses changes. 👍

2018-11-23 15:58 UTC, saurabhshri requested changes
Also, make sure config files have apt description too.

2018-11-23 15:58 UTC, saurabhshri commented on docs/installation.adoc
> +- Also creates an Admin User, with credentials from secret config (instance/config.py)
This seems redundant. It's not needed in description of any of the modes, but needs to be mentioned separately.

2018-11-24 16:45 UTC, saurabhshri requested changes
Looks good! :)

2018-11-24 16:45 UTC, saurabhshri commented on instance/config.py
> +    Summary:    Creates an admin User, with these credentials. All the operations (upload, processing,
```suggestion
    Summary:    Creates an admin User, with these credentials. In 'local' mode, all the operations (upload, processing,
```

2018-11-24 17:06 UTC, saurabhshri approved these changes

2018-11-24 17:09 UTC, merged