Added tests for users and files admin pages
saurabhshri/ccextractor-web pull request #8
Opened 2018-10-24 16:20 UTC by alufers

I have added tests got the users and files admin pages. Additionally I have created a function to login the user as an administrator for testing.

2018-10-24 17:36 UTC, saurabhshri requested changes
Hello @alufers ! Thank you for the PR! :) Looks like a nice start, but here are some changes that are needed.

Instead of creating your own login utility function, why not use the real login function which the webapp uses? You may create a dummy user in db and session in the `setUp` section of the test class. This way you'll test with the real result of login functions instead of the one you've created.

Also, instead of creating separate classes - could you please include those tests in `test_authentication.py` file?

Thanks again! :)

2018-10-24 18:59 UTC, alufers commented
Okay, I will move these tests.

2018-10-24 20:00 UTC, alufers commented
Hi! I have moved the tests, but I can't seem to be able to use the login endpoint in testing. Somehow the form doesn't validate and the controller doesn't even try checking the credentials. Maybe it's a problem with CSRF?

2018-10-25 12:48 UTC, saurabhshri commented
@alufers Hi, you're right. When sending request form unittest, you're not sending a CSRF token and hence invalidating the request. I'd suggest adding 
```
app.config['WTF_CSRF_ENABLED'] = False
```

in set-up section of test class. :) This should let you solve the problem.

2018-10-25 12:57 UTC, saurabhshri commented on tests/test_authentication.py
> +        self.assertIn(b'id="dataTable"', response.data)
Please add one more assert with specific data field (like you added in `TestFilesAdmin`) because `dataTable` is pretty generic.

2018-10-25 12:57 UTC, saurabhshri commented on tests/test_authentication.py
> +        self.assertIn(b'Uploaded Files', response.data)
Maybe change `Uploaded Files` to something which can only be there in admin's file section, like `<th>User ID</th>`?

2018-10-25 17:52 UTC, merged